### ISSUE TITLE
[feature request] re-create for mobile platform

### ISSUE THREAD

**Issue by op06072** [MajsoulPlus/majsoul-plus#104]
**描述您希望的解决方案**
I want to run this app with mobile platform.

**描述您希望的备选方案**
I want to re-create this app with React or another framework, but I'm not sure if it's possible.  Anyway, all I want is an app to run on a mobile platform.  Whether it's made in webview or native.

**Comment by Yesterday17** [comment]
It's not possible to migrate it to mobile platforms **directly** since Electron is not available on mobile platforms.

But you can implement the extension api. The corresponding source of this part is mostly electron-free(ipcMain can be ignored).

https://github.com/MajsoulPlus/majsoul-plus/blob/master/src/BaseManager.ts
https://github.com/MajsoulPlus/majsoul-plus/blob/master/src/extension/manager.ts
https://github.com/MajsoulPlus/majsoul-plus/blob/master/src/resourcepack/manager.ts
https://github.com/MajsoulPlus/majsoul-plus/blob/master/src/server.ts

**Comment by op06072** [comment]
> It's not possible to migrate it to mobile platforms **directly** since Electron is not available on mobile platforms.
> 
> But you can implement the extension api. The corresponding source of this part is mostly electron-free(ipcMain can be ignored).
> 
> https://github.com/MajsoulPlus/majsoul-plus/blob/master/src/BaseManager.ts
> https://github.com/MajsoulPlus/majsoul-plus/blob/master/src/extension/manager.ts
> https://github.com/MajsoulPlus/majsoul-plus/blob/master/src/resourcepack/manager.ts
> https://github.com/MajsoulPlus/majsoul-plus/blob/master/src/server.ts

If so, does it mean that I have to create the new one using the four mentioned as a core?

**Comment by op06072** [comment]
> It's not possible to migrate it to mobile platforms **directly** since Electron is not available on mobile platforms.
> 
> But you can implement the extension api. The corresponding source of this part is mostly electron-free(ipcMain can be ignored).
> 
> https://github.com/MajsoulPlus/majsoul-plus/blob/master/src/BaseManager.ts
> https://github.com/MajsoulPlus/majsoul-plus/blob/master/src/extension/manager.ts
> https://github.com/MajsoulPlus/majsoul-plus/blob/master/src/resourcepack/manager.ts
> https://github.com/MajsoulPlus/majsoul-plus/blob/master/src/server.ts

And I have to write new logic for things like card lists, right?

**Comment by Yesterday17** [comment]
@op06072 Sure.

**Comment by op06072** [comment]
> @op06072 Sure.

That's bad news... Thank you for the answer.
